
// Generated by the ADS125H18 Sequencer Configuration Tool on 10/30/2024, 2:22:27 PM

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))
#define EXT_CLK_FREQ_MHZ (25.6) // Define a value between 0.5 and 26.2

/* Type definitions */
typedef struct {
    const uint8_t addr;
    const uint8_t value;
} RegisterConfig;

typedef struct {
    const uint8_t pageNumber;
    const RegisterConfig *configPointer;
    const int registerCount;
} PageConfig;

/* Global page */
RegisterConfig global_page_config[] = {
{ .addr = 0x20, .value = 0xC0 }, // SEQUENCER_CFG,
{ .addr = 0x21, .value = 0x01 }, // SEQUENCE_STEP_EN_0
};

RegisterConfig step0_first_step_config[] = {
{ .addr = 0x02, .value = 0x10 }, // STEP0_ADC_REF_CFG,
{ .addr = 0x0B, .value = 0x01 }, // STEP0_OW_SYSMON_CFG
{ .addr = 0x03, .value = 0x08 },  // set OSR to 1024
};


PageConfig ADS125H18_sequencer_config[] = {
    { .pageNumber = 0x00, .configPointer = global_page_config, .registerCount = ARRAY_SIZE(global_page_config) },
    { .pageNumber = 0x01, .configPointer = step0_first_step_config, .registerCount = ARRAY_SIZE(step0_first_step_config) },
    
};

#define SEQUENCE_SIZE (ARRAY_SIZE(ADS125H18_sequencer_config))
