// Generated by the ADS125H18 Sequencer Configuration Tool on 9/22/2026, 11:47:08 AM

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))
#define EXT_CLK_FREQ_MHZ (25.6) // Define a value between 0.5 and 26.2


typedef struct 
{
    const uint8_t addr;
    const uint8_t value;
} RegisterConfig;

typedef struct 
{
    const uint8_t pageNumber;
    const RegisterConfig *configPointer;
    const int registerCount;
} PageConfig;

RegisterConfig global_page_config[] = {
    {.addr = 0x10, .value = 0x10}, // CONVERSION_CTRL
    {.addr = 0x20, .value = 0x82}, // SEQUENCER_CFG
    {.addr = 0x21, .value = 0x90}, // SEQUENCE_STEP_EN_0
    {.addr = 0x22, .value = 0x2C}, // SEQUENCE_STEP_EN_1
    {.addr = 0x23, .value = 0x61}, // SEQUENCE_STEP_EN_2
    {.addr = 0x24, .value = 0x1E}, // SEQUENCE_STEP_EN_3
    {.addr = 0x25, .value = 0x01}, // FIFO_CFG
    {.addr = 0x26, .value = 0x01}, // FIFO_THRES_A_MSB
    {.addr = 0x27, .value = 0xFF}, // FIFO_THRES_A_LSB
};


RegisterConfig AIN0_RESN[] = {
    {.addr = 0x02, .value = 0x14}, // STEP4_ADC_REF_CFG
};

RegisterConfig AIN4_AIN5[] = {
    {.addr = 0x00, .value = 0x12}, // STEP7_AIN_CFG
    {.addr = 0x02, .value = 0x15}, // STEP7_ADC_REF_CFG
};

RegisterConfig AIN7_RESN[] = {
    {.addr = 0x00, .value = 0x07}, // STEP10_AIN_CFG
    {.addr = 0x02, .value = 0x15}, // STEP10_ADC_REF_CFG
};

RegisterConfig AIN12_AIN13[] = {
    {.addr = 0x00, .value = 0x16}, // STEP11_AIN_CFG
    {.addr = 0x02, .value = 0x1A}, // STEP11_ADC_REF_CFG
};

RegisterConfig AIN15_RESN[] = {
    {.addr = 0x00, .value = 0x0F}, // STEP13_AIN_CFG
    {.addr = 0x02, .value = 0x16}, // STEP13_ADC_REF_CFG
};

RegisterConfig TEMP_SENSOR[] = {
    {.addr = 0x02, .value = 0x12}, // STEP16_ADC_REF_CFG
    {.addr = 0x0B, .value = 0x02}, // STEP16_OW_SYSMON_CFG
};

RegisterConfig AVDD[] = {
    {.addr = 0x02, .value = 0x02}, // STEP21_ADC_REF_CFG
    {.addr = 0x0B, .value = 0x03}, // STEP21_OW_SYSMON_CFG
};

RegisterConfig IOVDD[] = {
    {.addr = 0x02, .value = 0x02}, // STEP22_ADC_REF_CFG
    {.addr = 0x0B, .value = 0x05}, // STEP22_OW_SYSMON_CFG
};

RegisterConfig OWCS_0[] = {
    {.addr = 0x02, .value = 0x1B}, // STEP25_ADC_REF_CFG
};

RegisterConfig OWCS_1[] = {
    {.addr = 0x02, .value = 0x1B}, // STEP26_ADC_REF_CFG
    {.addr = 0x0B, .value = 0x40}, // STEP26_OW_SYSMON_CFG
};

RegisterConfig OWCS_2[] = {
    {.addr = 0x02, .value = 0x19}, // STEP27_ADC_REF_CFG
};

RegisterConfig OWCS_3[] = {
    {.addr = 0x02, .value = 0x19}, // STEP28_ADC_REF_CFG
    {.addr = 0x0B, .value = 0x40}, // STEP28_OW_SYSMON_CFG
};

PageConfig ADS125H18_sequencer_config[] = {
    {.pageNumber = 0x00, .configPointer = global_page_config, .registerCount = ARRAY_SIZE(global_page_config)},
    {.pageNumber = 0x05, .configPointer = AIN0_RESN, .registerCount = ARRAY_SIZE(AIN0_RESN)},
    {.pageNumber = 0x08, .configPointer = AIN4_AIN5, .registerCount = ARRAY_SIZE(AIN4_AIN5)},
    {.pageNumber = 0x0B, .configPointer = AIN7_RESN, .registerCount = ARRAY_SIZE(AIN7_RESN)},
    {.pageNumber = 0x0C, .configPointer = AIN12_AIN13, .registerCount = ARRAY_SIZE(AIN12_AIN13)},
    {.pageNumber = 0x0E, .configPointer = AIN15_RESN, .registerCount = ARRAY_SIZE(AIN15_RESN)},
    {.pageNumber = 0x11, .configPointer = TEMP_SENSOR, .registerCount = ARRAY_SIZE(TEMP_SENSOR)},
    {.pageNumber = 0x16, .configPointer = AVDD, .registerCount = ARRAY_SIZE(AVDD)},
    {.pageNumber = 0x17, .configPointer = IOVDD, .registerCount = ARRAY_SIZE(IOVDD)},
    {.pageNumber = 0x1A, .configPointer = OWCS_0, .registerCount = ARRAY_SIZE(OWCS_0)},
    {.pageNumber = 0x1B, .configPointer = OWCS_1, .registerCount = ARRAY_SIZE(OWCS_1)},
    {.pageNumber = 0x1C, .configPointer = OWCS_2, .registerCount = ARRAY_SIZE(OWCS_2)},
    {.pageNumber = 0x1D, .configPointer = OWCS_3, .registerCount = ARRAY_SIZE(OWCS_3)},
};

#define SEQUENCE_SIZE (ARRAY_SIZE(ADS125H18_sequencer_config))
