
// Generated by the ADS125P08 Sequencer Configuration Tool on 1/8/2026, 3:55:30 PM

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))
#define EXT_CLK_FREQ_MHZ (25.6) // Define a value between 0.5 and 26.2

/* Type definitions */
typedef struct {
    const uint8_t addr;
    const uint8_t value;
} RegisterConfig;

typedef struct {
    const uint8_t pageNumber;
    const RegisterConfig *configPointer;
    const int registerCount;
} PageConfig;

/* Global page */
RegisterConfig global_page_config[] = {
{ .addr = 0x13, .value = 0x00 }, // REFERENCE_CFG
};

RegisterConfig step0_config[] = {
{ .addr = 0x03, .value = 0x0B }, // STEP0_FLTR1_CFG,
{ .addr = 0x0B, .value = 0x01 }, // STEP0_OW_SYSMON_CFG
};

PageConfig ADS125P08_sequencer_config[] = {
    { .pageNumber = 0x00, .configPointer = global_page_config, .registerCount = ARRAY_SIZE(global_page_config) },
{ .pageNumber = 0x01, .configPointer = step0_config, .registerCount = ARRAY_SIZE(step0_config)}
};

#define SEQUENCE_SIZE (ARRAY_SIZE(ADS125P08_sequencer_config))
